import Link from "next/link";
import "./globals.css";
import { Inter, Limelight } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const limelight = Limelight({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-limelight",
});

export const metadata = {
  title: "Neha Rastogi | Creative Designer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${limelight.variable}`}>
      <body className="relative bg-black text-white">{children}</body>
    </html>
  );
}
